server:
  port: 8080
  servlet:
    context-path: /flowable-modeler
spring:
  datasource:
    url: jdbc:mysql://192.168.239.128:3306/flowable?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: flowable-modeler
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    blobType: BLOB
    boolValue: TRUE
    prefix:
